### ISSUE TITLE
pre-commit hooks is not working as expected

### ISSUE THREAD

**Issue by BarisX** [dhatim/python-license-check#77]
First of all thanks for all effort for this lybrary.
```
  files: ^(.*requirements.*\.txt|setup\.cfg|setup\.py|pyproject\.toml|liccheck\.ini)$
```
This regex detect multiple `requirements.txt` file but when i deleted all others after it is still not working.

i set up `.pre-commit-config.yaml` as below:
```yaml
repos:
  - repo: local
    hooks:
    - id: liccheck
      name: Run Python License Checker
      description: Check license compliance of python requirements
      entry: liccheck
      args: []
      language: python
      files: ^(.*requirements.*\.txt|setup\.cfg|setup\.py|pyproject\.toml|liccheck\.ini)$
```

After first attempt:
```
Run Python License Checker...............................................Failed
- hook id: liccheck
- exit code: 2

usage: liccheck.EXE [-h] [-s STRATEGY_INI_FILE]
                    [-l {STANDARD,CAUTIOUS,PARANOID}]
                    [-r [REQUIREMENT_TXT_FILE]] [-R [REPORTING_TXT_FILE]]
                    [--no-deps]
liccheck.EXE: error: unrecognized arguments: server/project/google cloud functions/function-name/requirements.txt server/project/google cloud functions/function-name2/requirements.txt server/requirements.txt
```
I delete all others except one `requirements.txt`, run again:

```
Run Python License Checker...............................................Failed
- hook id: liccheck
- exit code: 2

usage: liccheck.EXE [-h] [-s STRATEGY_INI_FILE]
                    [-l {STANDARD,CAUTIOUS,PARANOID}]
                    [-r [REQUIREMENT_TXT_FILE]] [-R [REPORTING_TXT_FILE]]
                    [--no-deps]
liccheck.EXE: error: unrecognized arguments: server/requirements.txt
```
That seems arguments are not enough fitting for running.
```
- repo: local
  hooks:
  - id: liccheck
    name: Run Python License Checker
    description: Check license compliance of python requirements
    entry: liccheck
    args: 
    - -s server/liccheck.ini
    - -r server/requirements.txt
    language: python
    files: ^(.*requirements.*\.txt|setup\.cfg|setup\.py|pyproject\.toml|liccheck\.ini)$
```
after run again:
```
Run Python License Checker...............................................Failed
- hook id: liccheck
- exit code: 2

usage: liccheck.EXE [-h] [-s STRATEGY_INI_FILE]
                    [-l {STANDARD,CAUTIOUS,PARANOID}]
                    [-r [REQUIREMENT_TXT_FILE]] [-R [REPORTING_TXT_FILE]]
                    [--no-deps]
liccheck.EXE: error: unrecognized arguments: server/requirements.txt
```

All of tested in Windows 10.

**Comment by bagerard** [comment]
As @commonlawfeature pointed out, it's also working for me with the `pass_filenames: false`

Another tweak I had to do was use `language: system`, since this hook requires to be running in the virtual env that contains all the libraries
```
  - repo: https://github.com/dhatim/python-license-check
    rev: master
    hooks:
    - id: liccheck
      pass_filenames: false
      language: system
```

`pass_filenames: false` should be set in the .pre-commit-hooks.yaml file contained in this repo

If we don't set that flag, pre-commit will provide the liccheck entry point with any of the files filtered by `files: ^(.*requirements.*\.txt|setup\.cfg|setup\.py|pyproject\.toml|liccheck\.ini)$` 

Thus, it will try to call `liccheck requirements.txt setup.py` if you have these 2 files in the repository but liccheck isn't setup to work with positional argument like that so that's why it fails with `liccheck: error: unrecognized arguments: pyproject.toml requirements.txt setup.cfg`

I'll open a PR shortly with that fix
